name: Push to Docker Registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch commit ID
        run: |
          echo "COMMIT_ID=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t peekaboo51490/sky_server_build_server:latest .
          docker tag peekaboo51490/sky_server_build_server:${{ env.BRANCH_NAME }}-${{ env.COMMIT_ID }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        run: |
          docker push peekaboo51490/sky_server_build_server:latest
